FROM ubuntu:20.04
# MAINTAINER omw <contact@omw.wtf>
LABEL Description="Ubuntu 20.04 LTS LAMP stack."\
	Usage="docker run -d -p [HOST WWW PORT NUMBER]:80 -p [HOST DB PORT NUMBER]:3306 -v [HOST WWW DOCUMENT ROOT]:/var/www/html -v [HOST DB DOCUMENT ROOT]:/var/lib/mysql name" \
	Version="1.0"

RUN apt-get update
RUN apt-get upgrade -y
RUN ln -snf /usr/share/zoneinfo/$DATE_TIMEZONE /etc/localtime && echo $DATE_TIMEZONE > /etc/timezone

RUN apt-get install -y zip unzip
RUN apt-get install -y \
	php7.4 \
	php7.4-mysql
RUN apt-get install apache2 libapache2-mod-php7.4 -y
RUN apt-get install mariadb-common mariadb-server mariadb-client -y
RUN apt-get install git composer nano tree vim curl wget -y
RUN apt-get install netcat iputils-ping -y
RUN apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

RUN apt-get -y install openssh-server sudo

ENV LOG_STDOUT **Boolean**
ENV LOG_STDERR **Boolean**
ENV LOG_LEVEL warn
ENV ALLOW_OVERRIDE All
ENV DATE_TIMEZONE Asia/Bangkok
ENV TERM dumb

COPY app/ /var/www/html/
COPY run-lamp.sh /usr/sbin/
# COPY mysql/ /var/lib/mysql/

RUN useradd -ms /bin/bash master-mc && echo "master-mc:1234" | chpasswd

RUN a2enmod rewrite
RUN chmod +x /usr/sbin/run-lamp.sh
RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 777 /var/www/html
RUN chown -R mysql:mysql /var/lib/mysql
RUN rm /var/www/html/index.html

RUN service ssh start

EXPOSE 80
EXPOSE 3306

CMD ["/usr/sbin/run-lamp.sh"]
