version: '2'

services:
  testcomex:
    cap_add:
      - NET_ADMIN
    build: 
      context: ./comex
      dockerfile: dockerfile
    restart: unless-stopped
    # ports:
    #   - '8081:80'
    #   - "2222:22"
    #   - '20-21:20-21/tcp'
    #   - '40000-40009:40000-40009/tcp'
    networks:
      ex-networks:
        ipv4_address: 172.10.3.3
    
      in-networks:
        ipv4_address: 172.20.3.3

  testcomin:
    cap_add:
      - NET_ADMIN
    build: 
      context: ./comin
      dockerfile: dockerfile
    restart: unless-stopped
    # ports:
    #   - '8082:80'
    #   - '1880:1880'
    networks:
      in-networks:
        ipv4_address: 172.20.3.4

  mastervpn:
    cap_add:
      - NET_ADMIN
    build: 
      context: ./vpn
      dockerfile: dockerfile
    volumes:
      - ./vpn/openvpn-data:/etc/openvpn
    restart: unless-stopped
    ports:
      - '1194:1194/udp'
    networks:
      ex-networks:
        ipv4_address: 172.10.3.2

networks:
  ex-networks:
    name: aNetwork
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.3.0/24
          gateway: 172.10.3.1
  
  in-networks:
    name: bNetwork
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.3.0/24
          gateway: 172.20.3.1