version: '2'

services:
  comex:
    cap_add:
      - NET_ADMIN
    build: 
      context: ./comex
      dockerfile: dockerfile
    restart: unless-stopped
    networks:
      a-networks:
        ipv4_address: 172.10.3.3
    
      b-networks:
        ipv4_address: 172.20.3.3

  comin:
    cap_add:
      - NET_ADMIN
    build: 
      context: ./comin
      dockerfile: dockerfile
    restart: unless-stopped
    volumes:
     - ./comin/app:/var/www/html/
    ports:
      - '22:22'
      - '8082:80'
    networks:
      b-networks:
        ipv4_address: 172.20.3.4
      c-networks:
        ipv4_address: 172.30.3.4

  nodered:
    cap_add:
      - NET_ADMIN
    build: 
      context: ./nodered
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - '1880:1880'
    networks:
      c-networks:
        ipv4_address: 172.30.3.5

  mastervpn:
    cap_add:
      - NET_ADMIN
    build: 
      context: ./vpn
      dockerfile: dockerfile
    volumes:
      - ./vpn/openvpn-data:/etc/openvpn
    restart: unless-stopped
    ports:
      - '1194:1194/udp'
    networks:
      a-networks:
        ipv4_address: 172.10.3.2

  masterpi:
    cap_add:
      - NET_ADMIN
    build: 
      context: ./vpn
      dockerfile: dockerfile
    volumes:
      - ./vpn/openvpn-pi:/etc/openvpn
    restart: unless-stopped
    ports:
      - '1200:1194/udp'
    networks:
      c-networks:
        ipv4_address: 172.30.3.2

networks:
  a-networks:
    name: aNetwork
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.3.0/24
          gateway: 172.10.3.1
  
  b-networks:
    name: bNetwork
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.3.0/24
          gateway: 172.20.3.1

  c-networks:
    name: cNetwork
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.3.0/24
          gateway: 172.30.3.1