version: '2'

services:
  external:
    build: external
    ports:
      - "8081:80"
      - "2222:22"
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'
    volumes:
      - '/data:/home/user'
    networks:
      - external

networks:
  external: