version: '2'

services:
  testcomex:
    build: 
      context: ./comex
      dockerfile: dockerfile
    ports:
      - '8081:80'
      - "2222:22"
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'
    networks:
      ex-networks:
        ipv4_address: 172.16.3.2 
    
      in-networks:
        ipv4_address: 10.10.9.2 

  testcomin:
    build: 
      context: ./comin
      dockerfile: dockerfile
    ports:
      - '8082:80'
      - '1880:1880'
    networks:
      in-networks:
        ipv4_address: 10.10.9.3

  VPN:
    build: 
      context: ./vpn
      dockerfile: dockerfile
    ports:
      - '1194:1194/udp'
    networks:
      in-networks:
        ipv4_address: 10.10.9.3

networks:
  ex-networks:
    name: aNetwork
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.3.0/24
          gateway: 172.16.3.1
  
  in-networks:
    name: bNetwork
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.9.0/24
          gateway: 10.10.9.1