version: '2'

services:
  comex:
    cap_add:
      - NET_ADMIN
    build: 
      context: ./comex
      dockerfile: dockerfile
    restart: unless-stopped
    networks:
      a-networks:
        ipv4_address: 10.10.3.3
    
      b-networks:
        ipv4_address: 10.20.3.3

  comin:
    cap_add:
      - NET_ADMIN
    build: 
      context: ./comin
      dockerfile: dockerfile
    restart: unless-stopped
    volumes:
     - ./comin/app:/var/www/html/
    networks:
      b-networks:
        ipv4_address: 10.20.3.4
      c-networks:
        ipv4_address: 10.30.3.4

  nodered:
    cap_add:
      - NET_ADMIN
    build: 
      context: ./nodered
      dockerfile: dockerfile
    restart: unless-stopped
    networks:
      c-networks:
        ipv4_address: 10.30.3.5

  mastervpn:
    cap_add:
      - NET_ADMIN
    build: 
      context: ./vpn
      dockerfile: dockerfile-data
    volumes:
      - ./vpn/openvpn-data:/etc/openvpn
    restart: unless-stopped
    ports:
      - '1194:1194/udp'
    networks:
      a-networks:
        ipv4_address: 10.10.3.2

  # masterpi:
  #   cap_add:
  #     - NET_ADMIN
  #   build: 
  #     context: ./vpn
  #     dockerfile: dockerfile-pi
  #   volumes:
  #     - ./vpn/openvpn-pi:/etc/openvpn
  #   restart: unless-stopped
  #   ports:
  #     - '1200:1194/udp'
  #   networks:
  #     c-networks:
  #       ipv4_address: 10.30.3.2

networks:
  a-networks:
    name: aNetwork
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.3.0/24
          gateway: 10.10.3.1
  
  b-networks:
    name: bNetwork
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.3.0/24
          gateway: 10.20.3.1

  c-networks:
    name: cNetwork
    driver: bridge
    ipam:
      config:
        - subnet: 10.30.3.0/24
          gateway: 10.30.3.1