FROM ubuntu:20.04

#external

RUN apt-get update
RUN apt-get upgrade -y
RUN ln -snf /usr/share/zoneinfo/$DATE_TIMEZONE /etc/localtime && echo $DATE_TIMEZONE > /etc/timezone

RUN apt-get update
RUN apt-get install -y \
	php7.4 \
	php7.4-mysql
RUN apt-get install apache2 libapache2-mod-php7.4 -y
RUN apt-get install mariadb-common mariadb-server mariadb-client -y
RUN apt-get install net-tools -y
RUN apt-get install netcat iputils-ping -y
RUN apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip
RUN apt-get -y install openssh-server sudo
RUN apt-get -y install vsftpd
RUN apt-get -y install ftp

ENV DATE_TIMEZONE Asia/Bangkok

RUN rm -rf /var/www/html/index.html
COPY ./app /var/www/html/

#data
COPY ./mysql/loginadminuser.sql /var/lib/mysql/loginadminuser.sql

#copy config
COPY ./vsftpd.conf /etc/vsftpd.conf
RUN chmod 644 /etc/vsftpd.conf

#adduser
RUN useradd -ms /bin/bash master-mc && echo "master-mc:eD^LW5(EyZtW6ubu" | chpasswd
COPY ./ftpMeme/helpMe.png /home/master-mc/helpMe.png

#config command
COPY ./scripts/start /start
RUN chmod +x /start

#run ssh
RUN service ssh start

EXPOSE 20-21/tcp
EXPOSE 22
EXPOSE 80
EXPOSE 3306
EXPOSE 40000-40009:40000-40009/tcp

CMD ["/start"]