FROM ubuntu:20.04

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get update
RUN apt-get install software-properties-common -y
RUN apt-get install netcat iputils-ping -y
RUN apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

RUN apt-get install -y nodejs
RUN apt-get install -y npm
RUN npm install -g --unsafe-perm node-red

#nodered
COPY ./nodered/ /root/.node-red/

#config command
COPY ./scripts/start /start
RUN chmod +x /start

EXPOSE 1880

CMD ["/start"]