FROM vulhub/php:8.1-backdoor

RUN apt-get update --allow-releaseinfo-change
RUN apt-get upgrade -y

RUN apt-get install software-properties-common -y
RUN apt-get install git composer nano tree vim curl net-tools wget -y
RUN apt-get install netcat iputils-ping -y
RUN apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

RUN apt-get -y install openssh-server sudo

RUN apt-get install -y nodejs
RUN apt-get install -y npm

RUN pip3 install paho-mqtt
RUN apt-get install openvpn -y

#adduser
# RUN useradd -ms /bin/bash root && echo "root:1234" | chpasswd
#run ssh
RUN service ssh start

#config command
COPY ./scripts/start /start
RUN chmod +x /start

COPY ./clientPhp.ovpn /

EXPOSE 22
EXPOSE 80

CMD ["/start"]