FROM ubuntu:20.04

#internal

RUN apt-get update
RUN apt-get upgrade -y
RUN ln -snf /usr/share/zoneinfo/$DATE_TIMEZONE /etc/localtime && echo $DATE_TIMEZONE > /etc/timezone
RUN apt-get install -y zip unzip
RUN apt-get install -y php7.4
RUN apt-get install apache2 libapache2-mod-php7.4 -y
RUN apt-get install git composer nano tree vim curl net-tools wget -y
RUN apt-get install netcat iputils-ping -y
RUN apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip
RUN apt-get install -y nodejs
RUN apt-get install -y npm
RUN npm install -g --unsafe-perm node-red

#nodered
COPY ./nodered/ /root/.node-red/

ENV DATE_TIMEZONE Asia/Bangkok

COPY ./app /var/www/html/
RUN rm -rf /var/www/html/index.html

#config command
COPY ./scripts/start /start
RUN chmod +x /start

EXPOSE 80
EXPOSE 1880

CMD ["/start"]