#!/bin/bash

# service  --status-all
# /bin/bash -c "sudo openvpn /clientPhp.ovpn"
/bin/bash -c "route add -net 192.168.255.0 netmask 255.255.255.0 gw 172.30.3.2"
/bin/bash -c "route add -net 192.168.254.0 netmask 255.255.255.0 gw 172.30.3.2"
/bin/bash -c "/usr/sbin/sshd"
/bin/bash -c "php -S 0.0.0.0:80 -t /var/www/html"

/bin/bash -c "sleep infinity"