#!/bin/bash

# service  --status-all
/bin/bash -c "service apache2 start"
# /bin/bash -c "service apache2 start"
/bin/bash -c "node-red"
/bin/bash -c "route add -net 172.10.3.0 netmask 255.255.255.0 gw 172.10.3.1"
/bin/bash -c "sleep infinity"